# Generated by Django 5.2.1 on 2025-05-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('registration_document', models.FileField(blank=True, null=True, upload_to='charity_documents/')),
                ('aptos_wallet_address', models.CharField(max_length=100)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='charity_logos/')),
                ('is_verified', models.BooleanField(default=False)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Charities',
            },
        ),
    ]
