# Generated by Django 5.2.1 on 2025-05-14 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('charity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='impact_details', serialize=False, to='main.charity')),
                ('description', models.TextField(help_text="Describe the charity's impact, key achievements, and goals.", verbose_name='Impact Statement/Description')),
                ('metrics_reported', models.JSONField(blank=True, help_text="Flexible field for various metrics, e.g., {'lives_impacted': 1000, 'trees_planted': 5000}", null=True, verbose_name='Impact Metrics (JSON)')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Impact Report',
                'verbose_name_plural': 'Impact Reports',
            },
        ),
        migrations.AlterModelOptions(
            name='charity',
            options={'ordering': ['-date_registered'], 'verbose_name_plural': 'Charities'},
        ),
        migrations.AddField(
            model_name='charity',
            name='category',
            field=models.CharField(blank=True, choices=[('ENV', 'Environment'), ('EDU', 'Education'), ('HEA', 'Health & Medicine'), ('ANI', 'Animal Welfare'), ('ART', 'Arts & Culture'), ('HUM', 'Human Rights'), ('COM', 'Community Development'), ('DIS', 'Disaster Relief'), ('OTH', 'Other')], default='OTH', max_length=3, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='charity',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='charity',
            name='country_of_operation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country of Operation'),
        ),
        migrations.AddField(
            model_name='charity',
            name='embedding',
            field=models.JSONField(blank=True, help_text='Embedding of the charity description', null=True),
        ),
        migrations.AddField(
            model_name='charity',
            name='polkadot_wallet_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Polkadot Wallet Address'),
        ),
        migrations.AddField(
            model_name='charity',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tagline/Short Summary'),
        ),
        migrations.AddField(
            model_name='charity',
            name='year_founded',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Year Founded'),
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Campaign Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Campaign Description')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Budget (USD)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_campaigns', to='main.charity')),
            ],
            options={
                'verbose_name': 'Marketing Campaign',
                'verbose_name_plural': 'Marketing Campaigns',
                'ordering': ['charity', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Post Title/Headline')),
                ('content', models.TextField(verbose_name='Post Content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='marketing_posts_images/', verbose_name='Image/Visual')),
                ('platform', models.CharField(choices=[('IG', 'Instagram'), ('FB', 'Facebook'), ('TW', 'X (Twitter)'), ('LI', 'LinkedIn'), ('TT', 'TikTok'), ('BG', 'Blog Post'), ('OT', 'Other')], default='OT', max_length=2, verbose_name='Platform')),
                ('post_date', models.DateTimeField(verbose_name='Scheduled/Actual Post Date')),
                ('post_url', models.URLField(blank=True, null=True, verbose_name='URL to Live Post')),
                ('reach', models.PositiveIntegerField(blank=True, null=True, verbose_name='Reach (Optional)')),
                ('engagement_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Engagement Rate (%) (Optional)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Internal Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='main.marketingcampaign')),
            ],
            options={
                'verbose_name': 'Social Media Post',
                'verbose_name_plural': 'Social Media Posts',
                'ordering': ['campaign', '-post_date'],
            },
        ),
    ]
