# Generated by Django 5.2.1 on 2025-05-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_impact_alter_charity_options_charity_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='extracted_text_data',
            field=models.TextField(blank=True, help_text="Raw text extracted from the charity's website", null=True),
        ),
    ]
