# Generated by Django 5.2.1 on 2025-05-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_charity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='keywords',
            field=models.JSONField(blank=True, help_text="Keywords describing the charity's focus, extracted by AI", null=True),
        ),
    ]
