# Generated by Django 5.2.1 on 2025-05-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_charity_extracted_text_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
