# Generated by Django 5.2.1 on 2025-05-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_charity_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(max_length=255, verbose_name='Transaction Hash')),
                ('donor_address', models.CharField(max_length=255, verbose_name='Donor Address')),
                ('charity_name', models.CharField(max_length=255, verbose_name='Charity Name')),
                ('charity_wallet_address', models.CharField(max_length=255, verbose_name='Charity Wallet Address')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Amount')),
                ('currency', models.CharField(max_length=10, verbose_name='Currency')),
                ('blockchain', models.CharField(choices=[('APT', 'Aptos'), ('POL', 'Polkadot')], default='APT', max_length=3, verbose_name='Blockchain')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('status', models.CharField(default='success', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Donation Transaction',
                'verbose_name_plural': 'Donation Transactions',
                'ordering': ['-timestamp'],
                'unique_together': {('transaction_hash', 'blockchain')},
            },
        ),
    ]
