# Generated by Django 5.2.1 on 2025-08-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='embedding',
            field=models.JSONField(blank=True, help_text='Embedding of the movement summary for semantic matching', null=True),
        ),
    ]
