from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import HomeView, RegisterCharityView, CharityListView
# from . import api # Comment out or remove old api import
from . import api_views # Import new api_views

app_name = 'main'

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'charities', api_views.CharityViewSet, basename='charity')
router.register(r'impacts', api_views.ImpactViewSet, basename='impact')
router.register(r'marketing-campaigns', api_views.MarketingCampaignViewSet, basename='marketingcampaign')
router.register(r'social-posts', api_views.SocialPostViewSet, basename='socialpost')
router.register(r'donation-transactions', api_views.DonationTransactionViewSet, basename='donationtransaction')
router.register(r'movements', api_views.MovementViewSet, basename='movement')

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('register-charity/', RegisterCharityView.as_view(), name='register-charity'),
    path('charities/', CharityListView.as_view(), name='charity-list'),
    
    # API endpoints generated by the router
    path('api/', include(router.urls)),

    # New endpoint for preparing donation transaction
    path('api/prepare-donation-transaction/', api_views.PrepareDonationTransactionView.as_view(), name='prepare-donation-transaction'),

    # New endpoint for semantic charity search
    path('api/charity-semantic-search/', api_views.CharitySemanticSearchView.as_view(), name='charity-semantic-search'),

    # Old API endpoints (to be removed or commented out)
    # path('api/charities/featured/', api.featured_charities, name='api-featured-charities'),
    # path('api/charities/', api.all_charities, name='api-all-charities'),
    # path('api/charities/<int:pk>/', api.charity_detail, name='api-charity-detail'),
] 